### ISSUE TITLE
make it compatible with HTMLBars

### ISSUE THREAD

**Issue by ssendev** [eviltrout/ember-cloaking#35]
when used with HTMLBars the helper registration dosn't work

```js
if (Ember.HTMLBars) {
  Ember.Handlebars.helper('cloaked-collection', Ember.CloakedCollectionView);
}
```

works for me on ember canary but i am not sure how reliable the feature detection is

**Comment by rsutphin** [comment]
@ssendev, can you explain where you made this change? I tried putting it here:

https://github.com/eviltrout/ember-cloaking/blob/master/ember-cloaking.js#L444

...but that didn't work.

**Comment by ssendev** [comment]
```js
if (Ember.HTMLBars) {
  Ember.Handlebars.helper('cloaked-collection', Ember.CloakedCollectionView);
} else {
  Ember.Handlebars.registerHelper('cloaked-collection', function(options) {
```

**Comment by rsutphin** [comment]
Thanks. That's what I tried, but it didn't work on 1.10.0-beta4 for me. I'll keep looking into it.

**Comment by runspired** [comment]
Just a ping, if you are using the ember-cli version I'll be making any necessary changes for it to work this afternoon.

**Comment by moses** [comment]
@runspired Great, let me know when it's ready.

**Comment by mmwebster** [comment]
@runspired Is there a chance that making the above change to ember-cloaking, to support HTMLBars, introduces problems with the rest of the script? After changing the script to support HTMLBars (currently using Ember 1.9.0), the helper was successfully registered and on the page I was able to see the first item in the list I passed in to content. However, none of the other items that would be un-cloaked without any scrolling are shown. Also, when I scroll down I see the loading text but no other items in content are un-cloaked. In the inspector, the first item in content is the only element that is ever rendered.

**Comment by runspired** [comment]
@mmwebster a preliminary conversion for ember-cli worked (exporting the CollectionView from the components directory) worked as expected.  I would assume either your conversion method or something else is at issue.

**Comment by runspired** [comment]
@moses es6-flattened branch has htmlbars

**Comment by moses** [comment]
@runspired you're the best, thanks.

**Comment by jessiahr** [comment]
I am having trouble getting this to work with htmlbars in ember 1.12.0-beta.1. When the page renders I get:

   Uncaught TypeError: undefined is not a function
   (line 444) return Ember.Handlebars.helpers.view.call(this, Ember.CloakedCollectionView, options);

Is there some additional setup I need to do to use with htmlbars?

**Comment by runspired** [comment]
@jessiahr There is if you are using the globals version.  If you are using ember-cli you can install the es6-flattened branch.  That branch is stable and is being used in production.  If not, the helper needs changed ala https://github.com/runspired/ember-cloaking/blob/es6-flattened/addon/helpers/cloaked-collection.js

**Comment by jessiahr** [comment]
@runspired I am using ember-cli and I listed the es6-flattened branch in my bower.json file:
` "ember-cloaking": "https://github.com/runspired/ember-cloaking.git#es6-flattened"` 
Is this the correct branch?

**Comment by runspired** [comment]
That is the correct branch, but `return Ember.Handlebars.helpers.view.call(this, Ember.CloakedCollectionView, options);` is not code from the latest on it, you may need to do a fresh install.  `npm install "https://github.com/runspired/ember-cloaking.git#es6-flattened"` should be all you need.

**Comment by jessiahr** [comment]
@runspired I confirmed that I have the correct package version installed and if I navigate to `bower_components/ember-cloaking/addon/helpers/cloaked-collection.js` I do see the updated logic to support htmlbars. I am thinking that I am not including it correctly.
I assumed `Include ember-cloaking.js in your project.` means `app.import('bower_components/ember-cloaking/ember-cloaking.js');` but maybe that is only for the global version?
(ps. I am fairly new to ember and the whole npm/bower/brocfile system is still a bit confusing to me so I apologize if I am asking a question with an obvious answer.)

**Comment by runspired** [comment]
Correct, only the globals version requires an import or requires the bower package.  The ember-cli version is a complete addon that wires itself in and contains all it's dependencies.  If you have the bower version, you may uninstall it.

**Comment by runspired** [comment]
I think the docs on the es6-flattened branch may still incorrectly say to do a bower install.  The bower install is only for globals, npm install works for everything else.  There is no needed blueprint, so this is the same as running `ember install:addon https://github.com/runspired/ember-cloaking.git#es6-flattened`

**Comment by msounthar** [comment]
Ember Cloaking addon is not working now with ember version 1.11.1
There is a undefined error in the line,
 
this.firstNode.parentNode

I speculate , This might have to do with the new changes to the morph code like mentioned here
https://github.com/emberjs/list-view/issues/209
or changes to the collection view as mentioned in the release notes here,
http://emberjs.com/blog/2015/04/04/ember-1-11-1-released.html

Same code worked great in ember 1.10.0

**Comment by perryqh** [comment]
I'm seeing the same issue as @msounthar with ember 1.11.1

**Comment by runspired** [comment]
I've unfortunately moved on from working on ember-cloaking to working on smoke-and-mirrors: https://github.com/runspired/smoke-and-mirrors

It's only got a short way to go before the `occlusion-collection` is capable of matching any use case ember-cloaking covered, and it's already more performant and has more possible applications.

**Comment by bsouid** [comment]
@runspired Smoke-and-mirrors looks cool but it is Ember CLI only. There is no alternative for those of us stuck on globals projects.

1.11.1 appears to not work unfortunately which means I would need to downgrade to use Ember-cloaking and there would be no upgrade ever again. Is there any hope of packaging smoke-and-mirrors as a JS file?

**Comment by bsouid** [comment]
Hmm I am actually also encountering the original issue still on 1.10.1:

Uncaught TypeError: Ember.Handlebars.helpers.view.call is not a function

This is with the latest zip of the es6 flattened branch and just changing the script includes in the demos to:

  <script src="http://builds.emberjs.com/tags/v1.10.1/ember-template-compiler.js"></script>
  <script src="http://builds.emberjs.com/tags/v1.10.1/ember.debug.js"></script>

The zip should have an up to date globals compatible version of the JS file right?

**Comment by eviltrout** [comment]
I have an experimental version working in 1.11 that I plan to put in git
soon.

**Comment by runspired** [comment]
@bsouid I'm not sure I ported the last few changes to the included globals build in that branch.

**Comment by jbrw1984** [comment]
Anxiously awaiting the git commit which supports 1.11.

**Comment by eviltrout** [comment]
I've merged the HTMLBars stuff into master. It's not as elegant as an Ember addon to install but it's working great in Discourse: https://github.com/eviltrout/ember-cloaking/commit/7cbecee70b39cd0d8da3a4bf558e96d5176a4cff
